### PR TITLE
Add Dockerfile and instructions for usage with Docker in README.md

### PR DESCRIPTION
**Pull request by raqbit**
The python docker image will automagically install the dependencies from requirements.txt.

### CODE REVIEW

**Comment by timo-schmid** [comment]
Thanks, looks good so far:

Could you also make the username & password configurable?

PS: This fixes issue #18 when merged!

**Comment by timo-schmid** [comment]
Actually, I'd say we merge this, we can make it confiugrable later!

**Comment by raqbit** [comment]
I can write some arg's, shouldn't take too long.

**Comment by villasv** [comment]
I already merged a PR in develop to configure accounts using a config file. The guy who did will still add multiple account support with config file, so I haven't merged to master yet.

**Comment by raqbit** [comment]
So.. Just realised CMD statements do NOT take variables. Manual editing is necessary (Not when the config pr merges)

~So, you can merge if you want.~

Edit: Found a workaround.

**Comment by villasv** [comment]
I'll merge without testing. When the multiaccount config is implemented you can retest the docker thing. But this should be merged to `develop`, not `master`. Please open a new PR.

**Pull request closed without merging**
